name: Testes de Mutação com Stryker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mutation-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes de mutação com Stryker
        run: npm run test_mutation

      - name: Deploy do relatório no GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports/mutation/html
          publish_branch: gh-pages
